<a href="https://colab.research.google.com/github/0007anuragsharma/Python-logical/blob/main/Logistic_Fine_tuning_13Feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
import numpy as np
import pandas as pd


In [147]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [148]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [149]:
from sklearn.impute import SimpleImputer

In [150]:
si = SimpleImputer()

In [151]:
df['fever']=si.fit_transform(df[['fever']])

In [152]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [153]:
from sklearn.preprocessing import LabelEncoder

In [154]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [155]:
lb = LabelEncoder()

In [156]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [157]:
df.head(2)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1

In [158]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [159]:
from sklearn.model_selection import train_test_split

In [160]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state=42)

In [161]:
from sklearn.linear_model import LogisticRegression

In [162]:
lr = LogisticRegression()

In [163]:
lr.fit(x_train,y_train)

LogisticRegression()

In [164]:
y_pred = lr.predict(x_test)

In [165]:
from sklearn.metrics import accuracy_score

In [166]:
accuracy_score(y_test , y_pred)

0.75

In [167]:
from sklearn.metrics import confusion_matrix

In [168]:
confusion_matrix(y_test , y_pred)

array([[9, 4],
       [1, 6]])

In [169]:
df = pd.read_csv("/content/Social_Network_Ads.csv")
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [170]:
from sklearn.preprocessing import LabelEncoder

In [171]:
lb = LabelEncoder()

In [172]:
df['Gender'] = lb.fit_transform(df['Gender'])

In [173]:
df.head(2)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0

In [174]:
from sklearn.model_selection import train_test_split

In [175]:
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [176]:
from sklearn.linear_model import LogisticRegression

In [177]:
lr = LogisticRegression()

In [178]:
lr.fit(x_train , y_train)

LogisticRegression()

In [179]:
y_pred = lr.predict(x_test)

In [180]:
from sklearn.metrics import accuracy_score

In [181]:
accuracy_score(y_test , y_pred)

0.75

In [182]:
from sklearn.metrics import confusion_matrix

In [183]:
confusion_matrix(y_test , y_pred)

array([[9, 4],
       [1, 6]])

In [184]:
df.shape

(400, 5)

In [185]:
df = pd.read_csv('/content/placement.csv')
df.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [186]:
from sklearn.model_selection import train_test_split

In [187]:
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size= 0.2 , random_state= 42)

In [188]:
from sklearn.linear_model import LogisticRegression

In [189]:
lr = LogisticRegression()

In [190]:
lr.fit(x_train , y_train)

LogisticRegression()

In [191]:
y_pred = lr.predict(x_test)

In [192]:
from sklearn.metrics import accuracy_score

In [193]:
accuracy_score(y_test , y_pred)

0.75

In [194]:
from sklearn.metrics import confusion_matrix

In [195]:
confusion_matrix(y_test , y_pred)

array([[9, 4],
       [1, 6]])

In [196]:
param_grid = [
    {'penalty':['l1','l2','elasticnet','none'],
    'C' : np.logspace(-4,4,20),
    'solver': ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter'  : [100,1000,2500,5000]
}
]


In [197]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(lr,param_grid = param_grid, cv = 3, verbose=True,n_jobs=-1)
clf


GridSearchCV(cv=3, estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                          'max_iter': [100, 1000, 2500, 5000],
                          'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                          'solver': ['lbfgs', 'newton-cg', 'liblinear', 'sag',
                                     'saga']}],
             verbose=True)

In [198]:
best_clf = clf.fit(x_train,y_train)
best_clf.best_estimator_


Fitting 3 folds for each of 1600 candidates, totalling 4800 fits


/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
3120 fits failed out of a total of 4800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_s

LogisticRegression(C=0.03359818286283781, solver='sag')

In [199]:
print(f'Accuracy - : {best_clf.score(x_train,y_train):.3f}')


Accuracy - : 0.550


In [200]:
df = pd.read_csv("/content/insurance.csv")
df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [201]:
from sklearn.preprocessing import LabelEncoder

In [202]:
lb = LabelEncoder()

In [203]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [204]:
df.head(2)

age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523

In [205]:
x = df.drop(columns = ['charges'])
y = df['charges']

In [206]:
from sklearn.model_selection import train_test_split

In [207]:
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size= 0.2 , random_state= 42)

In [209]:
from sklearn.linear_model import LinearRegression

In [210]:
lr = LinearRegression()

In [211]:
lr.fit(x_train,y_train)

LinearRegression()

In [212]:
y_pred = lr.predict(x_test)

In [213]:
from sklearn.metrics import r2_score

In [214]:
r2_score(y_test , y_pred)

0.7833463107364539

In [220]:
param_space = {'copy_X': [True,False],
               'fit_intercept': [True,False],
               'n_jobs': [1,5,10,15,None],
               'positive':[True,False]}

In [222]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(lr, param_space,cv=5)

In [223]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LinearRegression(),
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [1, 5, 10, 15, None],
                         'positive': [True, False]})

In [224]:
print(f"Best Score: {grid_search.best_score_}")

Best Score: 0.7345240790812606
