<a href="https://colab.research.google.com/github/0007anuragsharma/Python-logical/blob/main/Naive_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Naive Bayes Algorithm ===>
# The Naive Bayes algorithm is a family of simple yet powerful probabilistic classifiers based on applying Bayes' theorem with
# Strong (naive) independence assumptions between the features. It's particularly popular for text classification tasks such as
# spam detection, sentiment analysis, and document categorization.
# There are several types of Naive Bayes classifiers, depending on the nature of the feature data:
# Gaussian Naive Bayes: Assumes that the features follow a normal (Gaussian) distribution. It's used for continuous data.
# Multinomial Naive Bayes: Used for discrete data, particularly in text classification where features represent word frequencies.
# Bernoulli Naive Bayes: Assumes binary features (Os and Is), used for binary/boolean features, such as in text classification
# tasks where the presence or absence Of a word is considered. Steps Of Naive Bayes Algorithm Training Phase:
# Calculate the prior probability for each class. Calculate the likelihood for each feature given each class. If using Gaussian
# Naive Bayes, calculate the mean and variance Of the features for each class




In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("/content/Social_Network_Ads.csv",
                 usecols = ['Age','EstimatedSalary','Purchased'])
df.head(2)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0

In [23]:
x = df.drop(columns = ['Purchased']) #Independent colum
y = df['Purchased']

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc = StandardScaler()

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test , y_train , y_test = train_test_split(x,y,
                                                      test_size = 0.2,
                                                      random_state = 23)

In [28]:
x_train_new = sc.fit_transform(x_train)

In [29]:
x_test_new = sc.transform(x_test)

In [30]:
# from sklearn.naive_bayes import Burnollinb
from sklearn.naive_bayes import GaussianNB,MultinomialNB , BernoulliNB

classifier = GaussianNB()

In [31]:
classifier.fit(x_train_new, y_train)

GaussianNB()

In [42]:
y_pred = classifier.predict(x_test_new)

In [43]:
y_pred


array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
cn = confusion_matrix(y_test,y_pred)

In [46]:
y_test.shape

(80,)

In [47]:
y_pred.shape

(80,)

In [48]:
cn

array([[48,  2],
       [ 5, 25]])

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
accuracy_score(y_test , y_pred)

0.9125

In [53]:
from sklearn.metrics import precision_score

# Assuming y_true and y_pred are the true and predictied lables respectivly
precision = precision_score(y_test , y_pred)

In [54]:
precision

0.9259259259259259

In [56]:
from sklearn.metrics import recall_score

# Assuming y_true and y_pred are the true and predicted labels respectively
recall = recall_score(y_test, y_pred)

In [57]:
recall

0.8333333333333334

In [61]:
df = pd.read_csv("/content/titanic.csv")

In [62]:
df.head(2)

PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male   
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
0  34.5      0      0  330911  7.8292   NaN        Q  
1  47.0      1      0  363272  7.0000   NaN        S

In [63]:
df.drop(columns = {"Ticket","Embarked","Name","Fare","PassengerId","Cabin"},inplace=True)

In [64]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
dtype: int64

In [65]:
from sklearn.impute import SimpleImputer

In [66]:
si = SimpleImputer()

In [67]:
df['Age'] = si.fit_transform(df[['Age']])

In [68]:
from sklearn.preprocessing import LabelEncoder

In [69]:
lb = LabelEncoder()

In [70]:
df['Sex'] = lb.fit_transform(df['Sex'])


In [71]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [72]:
x= df.drop(columns = {"Survived"})
y = df["Survived"]

In [73]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [74]:
sc = StandardScaler()

In [75]:
x_train_new = sc.fit_transform(x_train)
x_test_new = sc.transform(x_test)

In [76]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB

In [77]:
classifier = GaussianNB()

In [78]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [79]:
y_pred = classifier.predict(x_test_new)

In [80]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [81]:
classifier.score(x_test_new,y_test)

1.0

In [82]:
from sklearn.metrics import confusion_matrix , precision_score , recall_score , f1_score

In [83]:
cm = confusion_matrix(y_test,y_pred)

In [84]:
cm

array([[50,  0],
       [ 0, 34]])

In [85]:
precision_score(y_test,y_pred)

1.0

In [86]:
recall_score(y_test,y_pred)

1.0

In [87]:
f1_score(y_test,y_pred)

1.0