<a href="https://colab.research.google.com/github/0007anuragsharma/Python-logical/blob/main/numpy_18_jan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [4]:
np.random.seed(1)

a = np.random.randint(1,10,4)
a

array([6, 9, 6, 1])

In [7]:
# View method mean modification in original array


a = np.array([10,20,30,40,50,60,70,80,90])
b = a[3:5]
b[:] = 0
b
a

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [9]:
# copy method will not update your orginal array

a = np.array([10,20,30,40,50,60,70,80,90])
b = a[3:5].copy()

b[:] = 0
b
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
a = np.random.randint(1,50,12)
a

array([43, 29, 30, 15,  5, 24, 24, 42, 31, 33, 23, 14])

In [14]:
a.shape

(12,)

In [16]:
a.reshape(2,6)

array([[43, 29, 30, 15,  5, 24],
       [24, 42, 31, 33, 23, 14]])

In [17]:
a.reshape(6,2)

array([[43, 29],
       [30, 15],
       [ 5, 24],
       [24, 42],
       [31, 33],
       [23, 14]])

In [18]:
a.reshape(4,3)

array([[43, 29, 30],
       [15,  5, 24],
       [24, 42, 31],
       [33, 23, 14]])

In [19]:
a.reshape(3,4)

array([[43, 29, 30, 15],
       [ 5, 24, 24, 42],
       [31, 33, 23, 14]])

In [21]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [23]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [25]:
a[a%2==0]


array([ 2,  4,  6,  8, 10, 12, 14])

In [26]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [28]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [29]:
b = np.arange(1,5).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [30]:
a+b

array([[2, 4],
       [6, 8]])

In [31]:
a-b

array([[0, 0],
       [0, 0]])

In [32]:
a/b

array([[1., 1.],
       [1., 1.]])

In [33]:
a.dot(b)   ###

array([[ 7, 10],
       [15, 22]])

In [35]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
a = np.array([10,20,30,40,50,10,10,10,20,20])

np.unique(a,return_index=True,return_counts=True)


(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 4]), array([4, 3, 1, 1, 1]))

In [38]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])



In [39]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])